### ISSUE TITLE
address objects missing essential variable validation 

### ISSUE THREAD

**Issue by speedupmate** [Adyen/adyen-magento2#1347]
**Describe the bug**

in https://github.com/Adyen/adyen-magento2/blob/9ea3288075262ebda0731a07306e287da455177f/view/frontend/web/js/view/payment/method-renderer/adyen-hpp-method.js#L581 

not even commenting on construction of this method containing methods etc but even with all this science it just misses essential validation if variables on address object are present or not. So as you can expect it fails when addres objects are not  yet populated thus failing on common checkout customisations including just moving payment step to first step after shipping methods by changing the layout file

So you end up with stuff like this: 

```
Uncaught TypeError: Unable to process binding "foreach: function(){return adyenPaymentMethods }"
Message: Unable to process binding "afterRender: function(){return renderCheckoutComponent() }"
Message: Cannot read properties of undefined (reading 'slice')
    at getStreetAndHouseNumberFromAddress (adyen-hpp-method.js:585:45)
    at UiClass.getFormattedAddress (adyen-hpp-method.js:624:26)
    at UiClass.buildComponentConfiguration (adyen-hpp-method.js:668:53)
    at Object.renderCheckoutComponent (adyen-hpp-method.js:252:50)
    at afterRender (eval at createBindingsStringEvaluator (knockout.js:3221:28), <anonymous>:3:174)
    at evaluateValueAccessor (knockout.js:3494:28)
    at knockout.js:3671:44
    at init (after-render.js:17:28)
    at knockout.js:3730:58
    at Object.ignore (knockout.js:1563:45)
    at knockout.js:3729:60
    at Object.arrayForEach (knockout.js:168:36)
    at applyBindingsToNodeInternal (knockout.js:3715:34)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:3573:56)
    at applyBindingsToDescendantsInternal (knockout.js:3555:29)
    at applyBindingsToNodeAndDescendantsInternal (knockout.js:3576:25)
```

**To Reproduce**
1.  add items to cart reach checkout while assigning payment methods to first step by editing checkout_index_index.xml layout file (just move the payment after shipping etc even if for testing)  
2. page loads without address data present, component is revealed and fails 

**Expected behavior**
Merchant is free to modify checkout and layout as they wish as its a documented way of doing things in devdocs 

**Additional context**

This is the first moment it shines, its a issue trough-out on every renderer provided and you can fix it by just checking if variable exists and if you need to perform your whatever you need to perform with the data 

you also see from the trace what causes the execution of this is invoked with afterRender on template 

https://github.com/Adyen/adyen-magento2/blob/4e33ad9771fbacc73a40b5330024634573a65d66/view/frontend/web/template/payment/hpp-form.html#L84

even if afterRender is a legit way to use ko to execute something on render then afterRender should really be your last resort of doing things in m2 checkout as checkout tries to be async but using afterRender makes it dependant on rendering waterfall . So scenarios like : h we loaded checkout but your payment method is not selected yet to be used but the template just rendered (even if hidden) and invoked something that is not selected or needed to be executed yet and that fails cause the data that you expect to be there without any validation is not there yet.

**Comment by tnaber** [comment]
Hi @speedupmate,

Thank you for opening this issue. We value your suggestions on our practices, could you link the specific devdocs you are talking about? Additionally, feel free to make your own contribution as an example for future implementations.

Cheers,
Titus

**Comment by speedupmate** [comment]
@tnaber 

sure , here you go :
https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_overview.html
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/layouts/layout-overview.html

**Comment by tnaber** [comment]
Hi @speedupmate,

As we have more merchant's experiencing this problem and a duplicate #1440 has been opened. I will be moving the discussion over to that issue and closing this one. 
Thank you for the information here :)

Cheers,
Titus

**Comment by tnaber** [comment]
Hi @speedupmate,
I'm having trouble recreating the issue using the steps you provided, could you share your checkout_index_index.xml file with me?

**Comment by speedupmate** [comment]
@tnaber you moved shipping to first step and tried with clear cache and session?

**Comment by tnaber** [comment]
Are you talking about Magento's checkout_index_index.xml or ours? What I tried was moving our payment methods in front of the shipping step by adding a sortOrder in our own checkout_index_index.xml, this did not have any effect (after clearing cache and session). I see you mean moving shipping to the first step but I don't get what you mean by that, isn't it already? Additionally, what do you do to successfully move it?

**Comment by jonathanribas** [comment]
I can confirm `afterRender` is causing this issue, same issue as https://github.com/Adyen/adyen-magento2/pull/1456#issuecomment-1096888675 and https://github.com/Adyen/adyen-magento2/issues/1461

As a temp workaround, I've implemented a sleep function on `renderSecureFields` on `8.2.0`:
[sleep.txt](https://github.com/Adyen/adyen-magento2/files/8485092/sleep.txt)

**Comment by kayintveen** [comment]
I tried implementing the patch on sleep.txt for #1461 but unfortunately for my issue its not working. 

i do see something else, not sure. if its related

```
Uncaught ReferenceError: Unable to process binding "ifnot: function(){return (getOriginKey()) }"
Message: getOriginKey is not defined
```

**Comment by jonathanribas** [comment]
@kayintveen, your error seems to be related to https://docs.adyen.com/development-resources/client-side-authentication#manage-allowed-origins
