### ISSUE TITLE
Multishipping - Cannot select Adyen Credit Card

### ISSUE THREAD

**Issue by matmarchant** [Adyen/adyen-magento2#1545]
**Describe the bug**
On the multishipping billing checkout stage, the Adyen Credit Card option is not selectable
adyen-cc-method.js:34 Uncaught TypeError: self.checkoutComponent.create is not a function
    at UiClass.renderSecureFields (adyen-cc-method.js:34:57)
    at UiClass.selectPaymentMethod (adyen-cc-method.js:25:18)
    at UiClass.selectPaymentMethod (wrapper.js:109:34)
    at HTMLInputElement.<anonymous> (knockout.js:4669:74)
    at HTMLInputElement.dispatch (jquery.js:5232:27)
    at HTMLInputElement.elemData.handle (jquery.js:4884:29)

**To Reproduce**
1. Go to Multishipping checkout
2. Add shipping addresses
3. Go to billing information
4. Attempt to select the Adyen Credit Card payment method
5. The payment method is unselectable and a console error is observed.

**Expected behavior**
The Adyen Credit Card payment method should be selectable.

**Magento version**
2.4.3p2

**Plugin version**
8.2.3

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 101.0.4951.64

**Comment by drew-webscale** [comment]
I have the same issue with sample data and the Luma theme. I am unable to use one page checkout with Adyen and when I try without one page checkout I get the error above:

```
adyen-cc-method.js:34 Uncaught TypeError: self.checkoutComponent.create is not a function
    at UiClass.renderSecureFields (adyen-cc-method.js:34:57)
    at UiClass.selectPaymentMethod (adyen-cc-method.js:25:18)
    at UiClass.selectPaymentMethod (wrapper.js:109:34)
    at HTMLInputElement.<anonymous> (knockout.js:4669:74)
    at HTMLInputElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)
```
