### ISSUE TITLE
Capture webhook not working in 8.3.0

### ISSUE THREAD

**Issue by dronerdk** [Adyen/adyen-magento2#1595]
In the latest version 8.3.0 we do not get the capture webhook.
We get this error when we try in magneto 2 to reprocess the webhook for capture.

Error: Call to a member function pay() on null in /var/www/droner.dk/public_html/vendor/magento/module-sales/Model/Order/Invoice.php:368
Stack trace:
#0 /var/www/droner.dk/public_html/generated/code/Magento/Sales/Model/Order/Invoice/Interceptor.php(149): Magento\Sales\Model\Order\Invoice->pay()
#1 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Invoice.php(196): Magento\Sales\Model\Order\Invoice\Interceptor->pay()
#2 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(1821): Adyen\Payment\Helper\Invoice->handleCaptureWebhook()
#3 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(420): Adyen\Payment\Helper\Webhook->handleManualCapture()
#4 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(344): Adyen\Payment\Helper\Webhook->handleOrderTransition()
#5 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Controller/Adminhtml/Notifications/WebhookReprocess.php(71): Adyen\Payment\Helper\Webhook->processNotification()
#6 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess->execute()
#7 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callParent()
#8 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/www/droner.dk/public_html/generated/code/Adyen/Payment/Controller/Adminhtml/Notifications/WebhookReprocess/Interceptor.php(23): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callPlugins()
#10 /var/www/droner.dk/public_html/vendor/magento/framework/App/Action/Action.php(111): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->execute()
#11 /var/www/droner.dk/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#12 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#13 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callParent()
#14 /var/www/droner.dk/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#16 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/droner.dk/public_html/generated/code/Adyen/Payment/Controller/Adminhtml/Notifications/WebhookReprocess/Interceptor.php(32): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callPlugins()
#18 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(245): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->dispatch()
#19 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#20 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#21 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#22 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#23 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#24 /var/www/droner.dk/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#25 /var/www/droner.dk/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#26 /var/www/droner.dk/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#27 /var/www/droner.dk/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#28 /var/www/droner.dk/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#29 {main}

**Comment by RokPopov** [comment]
Hi @dronerdk,

Thank you for opening this issue.

Please kindly provide us with the specific steps that you have taken to recapture the payment so we would be able to try to replicate the issue you are experiencing.

Looking forward to your reply,

Kind regards,
Rok,
Adyen

**Comment by dronerdk** [comment]
Hello

We did have module 8.2.5 and did not have any issues with processing webhooks from adyen.
Now we updated to 8.3.0 and it seems like the capture webhook from adyen is not processed properly in Mangeto.
I dont know if this is a module error or a webhook error, but we dont have any issues with 8.2.5.

We now face a lot of invoices in pending state because we did create the invoice and capture online. Adyen captures the payment but we do not get the capture webhook processed in magento.

If we now go to System -> Adyen Notifications Overview we can see all the capture webhook is not processed.
This is only for all the invoiced we made from 8.3.0. We did downgrade and now the processing works.
But we cannot get the pending invoices to a paid state.
We try to click reprocess webhook and then we get the error above.
<img width="1849" alt="Skærmbillede 2022-07-05 kl  10 49 57" src="https://user-images.githubusercontent.com/15999222/177289688-44f5ae6e-df9b-48f3-8efb-dd979b8d0c52.png">

**Comment by dronerdk** [comment]
Thanks Rok for fast respons.
When you have a quick fix please let me know so we can get the missing hooks reprocesesd.

**Comment by jonathanribas** [comment]
@candemiralp @RokPopov, unfortunately your fix from https://github.com/Adyen/adyen-magento2/pull/1596 is not resolving this issue as we have the problem on `8.3.2` too.

**Comment by RokPopov** [comment]
Hey @jonathanribas,

This does indeed seem strange. I have re-tested this on the version you mentioned, and the CAPTURE notification is getting processed accordingly in the default environment:
<img width="1356" alt="Screen Shot 2022-08-02 at 18 23 50" src="https://user-images.githubusercontent.com/59090063/182424763-41b6c74c-174c-4232-89d8-47588cc56e82.png">

Could you please elaborate a bit on what specific error are you seeing when the notification is trying to get processed?

Looking forward to your reply,

Kind regards,
Rok,
Adyen

**Comment by jonathanribas** [comment]
> In the latest version 8.3.0 we do not get the capture webhook. We get this error when we try in magneto 2 to reprocess the webhook for capture.
> 
> Error: Call to a member function pay() on null in /var/www/droner.dk/public_html/vendor/magento/module-sales/Model/Order/Invoice.php:368 Stack trace: #0 /var/www/droner.dk/public_html/generated/code/Magento/Sales/Model/Order/Invoice/Interceptor.php(149): Magento\Sales\Model\Order\Invoice->pay() #1 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Invoice.php(196): Magento\Sales\Model\Order\Invoice\Interceptor->pay() #2 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(1821): Adyen\Payment\Helper\Invoice->handleCaptureWebhook() #3 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(420): Adyen\Payment\Helper\Webhook->handleManualCapture() #4 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Helper/Webhook.php(344): Adyen\Payment\Helper\Webhook->handleOrderTransition() #5 /var/www/droner.dk/public_html/vendor/adyen/module-payment/Controller/Adminhtml/Notifications/WebhookReprocess.php(71): Adyen\Payment\Helper\Webhook->processNotification() #6 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess->execute() #7 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callParent() #8 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception{closure}() #9 /var/www/droner.dk/public_html/generated/code/Adyen/Payment/Controller/Adminhtml/Notifications/WebhookReprocess/Interceptor.php(23): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callPlugins() #10 /var/www/droner.dk/public_html/vendor/magento/framework/App/Action/Action.php(111): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->execute() #11 /var/www/droner.dk/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch() #12 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch() #13 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callParent() #14 /var/www/droner.dk/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception{closure}() #15 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() #16 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->Magento\Framework\Interception{closure}() #17 /var/www/droner.dk/public_html/generated/code/Adyen/Payment/Controller/Adminhtml/Notifications/WebhookReprocess/Interceptor.php(32): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->___callPlugins() #18 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(245): Adyen\Payment\Controller\Adminhtml\Notifications\WebhookReprocess\Interceptor->dispatch() #19 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse() #20 /var/www/droner.dk/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest() #21 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #22 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #23 /var/www/droner.dk/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}() #24 /var/www/droner.dk/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #25 /var/www/droner.dk/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #26 /var/www/droner.dk/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #27 /var/www/droner.dk/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch() #28 /var/www/droner.dk/public_html/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #29 {main}

We have this error too.

**Comment by RokPopov** [comment]
Hey @jonathanribas,

Please correct me if I am wrong, as I understand you are getting this error when reprocessing the CAPTURE notifications for orders that were made with the version before the fix was introduced? 
This does seem correct, the orders that were made in the version that wrongfully processed the CAPTURE notifications, cannot be reprocessed even when you update to a version that contains the fix. The way to do that would be to run the following script manually for each of the unprocessed notifications:
```
SET @CAPTURE_PSPREFERENCE = 'PUT YOUR CAPTURE NOTIFICATION PSPREFERENCE HERE';

SELECT @ORIGINAL_REFERENCE := original_reference FROM adyen_notification WHERE pspreference = @CAPTURE_PSPREFERENCE;
SELECT @ENTITYID := entity_id FROM sales_invoice WHERE transaction_id LIKE "'%" + @ORIGINAL_REFERENCE + "%'";
UPDATE adyen_invoice SET invoice_id = @ENTITYID WHERE pspreference = @CAPTURE_PSPREFERENCE;`
```

I hope this helps.

Kind regards,
Rok,
Adyen

**Comment by jonathanribas** [comment]
Hi @RokPopov, issue happens for orders placed with updated module version.

**Comment by Morerice** [comment]
Hi @jonathanribas,

Would it be possible to check what the output of:
  * `$adyenInvoiceObject->getInvoiceId()` and
  * `$magentoInvoice`

[here](https://github.com/Adyen/adyen-magento2/blob/8.3.0/Helper/Invoice.php#L193) for the cases where this issue is occurring?

Thanks,
Jean
Adyen

**Comment by jonathanribas** [comment]
Hi @Morerice, someone from my team will take a look at it this morning and we will let you know.

**Comment by jonathanribas** [comment]
Hi @Morerice, we noticed we were missing a parameter in one of our Adyen preference constructor that was causing this issue.
We will run further tests next week to make sure everything is ok on Adyen's module version `8.3.3` too.
