### ISSUE TITLE
 Deprecated Functionality: number_format(): Passing null to parameter #1 ($num) of type float is deprecated

### ISSUE THREAD

**Issue by ryanpalmerweb** [Adyen/adyen-magento2#1942]
Hi Adyen,

We are seeing the following message appearing in our order history for MobilePay orders

Deprecated Functionality: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in ... vendor/adyen/module-payment/Helper/Data.php on line 372

We are using version 8.13 of the Adyen module and PHP 8.1

Thanks,
Ryan

**Comment by Morerice** [comment]
Hi @ryanpalmerweb,

Thanks for opening this issue and apologies for the delayed response. Are you seeing this error message for all payments using MobilePay or only a select few?

Also, line 372 of `Data.php` on 8.13.0 points to a [doc block](https://github.com/Adyen/adyen-magento2/blob/58d86ce58be1f3f974f541a584435e7fc2c2a0fe/Helper/Data.php#L372). Can you check if you have modified the `Data.php?

Regards,
Jean
Adyen

**Comment by Morerice** [comment]
Hi @ryanpalmerweb,

We will be closing this issue due to inactivity. However if the issue persists, we still encourage you to open a ticket with our support team by sending a mail to support@adyen.com.

Regards,
Jean
Adyen

**Comment by maaarghk** [comment]
@Morerice  please check out @thomas-kl1 pull request. this bug causes a crash when handling notifications:

```
[2023-07-04T10:50:04.053170+00:00] AdyenLoggerTest.ADYEN_NOTIFICATION: Critical error occurred. Notification 94406 had an error: Deprecated Functionality: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in vendor/adyen/module-payment/Helper/Data.php on line 376 
 #0 [internal function]: Magento\Framework\App\ErrorHandler->handler()
#1 vendor/adyen/module-payment/Helper/Data.php(376): number_format()
#2 vendor/adyen/module-payment/Helper/AdyenOrderPayment.php(128): Adyen\Payment\Helper\Data->formatAmount()
#3 vendor/adyen/module-payment/Helper/Webhook/CaptureWebhookHandler.php(101): Adyen\Payment\Helper\AdyenOrderPayment->refreshPaymentCaptureStatus()
#4 vendor/adyen/module-payment/Helper/Webhook.php(191): Adyen\Payment\Helper\Webhook\CaptureWebhookHandler->handleWebhook()
#5 vendor/adyen/module-payment/Model/Queue/Notification/Consumer.php(38): Adyen\Payment\Helper\Webhook->processNotification()
```

in our case total_captured in adyen_order_payment is null which is probably some other problem - the order was manually captured in the adyen UI and not through creating a magento invoice.

I think fixing the float thing is good but probably would make sense to have something that records a useful error message and marks the webhook as errored so that it doesn't keep retrying  and hitting this number_format issue?
