### ISSUE TITLE
Manual run adyen:webhook:run

### ISSUE THREAD

**Issue by ruggeroland** [Adyen/adyen-magento2#2153]
**Magento version**
[e.g. 2.4.5-p1]

**Plugin version**
[e.g. 8.19]

**Describe the bug**

When run from ssh

php bin/magento adyen:webhook:run
I always get this error

Magento\Store\Model\App\Emulation::_restoreInitialDesign(): Argument #1 ($initialDesign) must be of type array, null given, called in /var/www/html/magento/vendor/magento/module-store/Model/App/Emulation.php on line 182#0 /var/www/html/magento/vendor/magento/module-store/Model/App/Emulation.php(182): Magento\Store\Model\App\Emulation->_restoreInitialDesign()
#1 /var/www/html/magento/vendor/magento/module-payment/Helper/Data.php(234): Magento\Store\Model\App\Emulation->stopEnvironmentEmulation()
#2 /var/www/html/magento/vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php(187): Magento\Payment\Helper\Data->getInfoBlockHtml()
#3 /var/www/html/magento/vendor/magento/module-sales/Model/Order/Email/Sender/InvoiceSender.php(137): Magento\Sales\Model\Order\Email\Sender\InvoiceSender->getPaymentHtml()
#4 /var/www/html/magento/vendor/adyen/module-payment/Helper/Invoice.php(216): Magento\Sales\Model\Order\Email\Sender\InvoiceSender->send()
#5 /var/www/html/magento/vendor/adyen/module-payment/Helper/Webhook/AuthorisationWebhookHandler.php(220): Adyen\Payment\Helper\Invoice->createInvoice()
#6 /var/www/html/magento/vendor/adyen/module-payment/Helper/Webhook/AuthorisationWebhookHandler.php(127): Adyen\Payment\Helper\Webhook\AuthorisationWebhookHandler->handleAutoCapture()
#7 /var/www/html/magento/vendor/adyen/module-payment/Helper/Webhook/AuthorisationWebhookHandler.php(93): Adyen\Payment\Helper\Webhook\AuthorisationWebhookHandler->handleSuccessfulAuthorisation()
#8 /var/www/html/magento/vendor/adyen/module-payment/Helper/Webhook.php(191): Adyen\Payment\Helper\Webhook\AuthorisationWebhookHandler->handleWebhook()
#9 /var/www/html/magento/vendor/adyen/module-payment/Cron/WebhookProcessor.php(132): Adyen\Payment\Helper\Webhook->processNotification()
#10 /var/www/html/magento/vendor/adyen/module-payment/Cron/WebhookProcessor.php(84): Adyen\Payment\Cron\WebhookProcessor->doProcessWebhook()
#11 /var/www/html/magento/generated/code/Adyen/Payment/Cron/WebhookProcessor/Proxy.php(95): Adyen\Payment\Cron\WebhookProcessor->execute()
#12 /var/www/html/magento/vendor/adyen/module-payment/Console/Command/WebhookProcessorCommand.php(35): Adyen\Payment\Cron\WebhookProcessor\Proxy->execute()
#13 /var/www/html/magento/vendor/symfony/console/Command/Command.php(255): Adyen\Payment\Console\Command\WebhookProcessorCommand->execute()
#14 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#15 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Adyen\Payment\Console\Command\WebhookProcessorCommand\Interceptor->___callParent()
#16 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(153): Adyen\Payment\Console\Command\WebhookProcessorCommand\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/html/magento/generated/code/Adyen/Payment/Console/Command/WebhookProcessorCommand/Interceptor.php(23): Adyen\Payment\Console\Command\WebhookProcessorCommand\Interceptor->___callPlugins()
#18 /var/www/html/magento/vendor/symfony/console/Application.php(1021): Adyen\Payment\Console\Command\WebhookProcessorCommand\Interceptor->run()
#19 /var/www/html/magento/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#20 /var/www/html/magento/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#21 /var/www/html/magento/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#22 /var/www/html/magento/bin/magento(23): Symfony\Component\Console\Application->run()
#23 {main}

Thanks

**Comment by candemiralp** [comment]
Hello @ruggeroland,

Thank you for raising this issue. Unfortunately, we tested the case on the same version of plugin and PHP8 - PHP7 and we are not able to reproduce the issue with the given information.

Could you please narrow down the scope a bit? Which webhook event are you trying to trigger? Any additional information might be useful to debug the issue.

Best Regards,
Can

**Comment by candemiralp** [comment]
Closing this issue since this issue requires more information and no activity for a while.

**Comment by pixiejohn** [comment]
Ive got the same problem with orders webhooks when the user logged in and makes the purchase.
If the user if not logged in the webhook command works as expected.
I dont know if thats any help but certainly something i am see in the 9.0.2 version in test mode.
