### ISSUE TITLE
[ECP-8903] RabbitMQ not able to Process Webhooks

### ISSUE THREAD

**Issue by maaarghk** [Adyen/adyen-magento2#2471]
Something about how the webhooks are serialised and added to the queue results in the created / updated dates being strings rather than DateTimes, so the queue consumer process exits with this TypeError:

```
There is an error in /var/www/html/vendor/adyen/module-payment/Model/Notification.php at line: 268
Adyen\Payment\Model\Notification::setCreatedAt(): Argument #1 ($createdAt) must be of type DateTime, string given, called in /var/www/html/vendor/magento/framework/Webapi/ServiceInputProcessor.php on line 327#0 /var/www/html/vendor/magento/framework/Webapi/ServiceInputProcessor.php(327): Adyen\Payment\Model\Notification->setCreatedAt()
#1 /var/www/html/vendor/magento/framework/Webapi/ServiceInputProcessor.php(524): Magento\Framework\Webapi\ServiceInputProcessor->_createFromArray()
#2 /var/www/html/vendor/magento/framework-message-queue/MessageEncoder.php(153): Magento\Framework\Webapi\ServiceInputProcessor->convertValue()
#3 /var/www/html/vendor/magento/framework-message-queue/MessageEncoder.php(104): Magento\Framework\MessageQueue\MessageEncoder->convertMessage()
#4 /var/www/html/vendor/magento/framework-message-queue/Consumer.php(160): Magento\Framework\MessageQueue\MessageEncoder->decode()
#5 /var/www/html/vendor/magento/framework-message-queue/Consumer.php(241): Magento\Framework\MessageQueue\Consumer->dispatchMessage()
#6 /var/www/html/vendor/magento/framework-amqp/Queue.php(150): Magento\Framework\MessageQueue\Consumer->Magento\Framework\MessageQueue\{closure}()
#7 [internal function]: Magento\Framework\Amqp\Queue->Magento\Framework\Amqp\{closure}()
#8 /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1055): call_user_func()
#9 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_deliver()
#10 /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(220): call_user_func()
#11 /var/www/html/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\Channel\AbstractChannel->dispatch()
#12 /var/www/html/vendor/magento/framework-amqp/Queue.php(162): PhpAmqpLib\Channel\AbstractChannel->wait()
#13 /var/www/html/vendor/magento/framework-message-queue/Consumer.php(135): Magento\Framework\Amqp\Queue->subscribe()
#14 /var/www/html/vendor/magento/module-message-queue/Console/StartConsumerCommand.php(94): Magento\Framework\MessageQueue\Consumer->process()
#15 /var/www/html/vendor/symfony/console/Command/Command.php(298): Magento\MessageQueue\Console\StartConsumerCommand->execute()
#16 /var/www/html/generated/code/Magento/MessageQueue/Console/StartConsumerCommand/Proxy.php(143): Symfony\Component\Console\Command\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(1040): Magento\MessageQueue\Console\StartConsumerCommand\Proxy->run()
#18 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#19 /var/www/html/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#20 /var/www/html/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun()
#21 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#22 {main}
```

I've had to patch it by removing the type on the function variable and converting it to a DateTime if it is a string.

**Comment by maaarghk** [comment]
BTW: module 9.0.7. php-api-library 17.0.0. mage 2.4.6-p3. rabbitmq 3.8.2

**Comment by khushboo-singhvi** [comment]
Hello @maaarghk,

Thank you for bringing this to our attention. We want to assure you that we are actively working on the issue, and there is already an internal ticket open for it. The good news is that the fix is in progress, and you can expect it to be included in our upcoming release.

We appreciate your patience and understanding as we work to address this. If you have any further questions or if there's anything else you'd like to discuss, feel free to let us know.

Regards
Khushboo

**Comment by maaarghk** [comment]
Will there be a 9.0.8 when it's fixed or are you sticking to the fortnightly release schedule?

**Comment by mourjohn** [comment]
During creating the object in the consumer, Magento wants to set the value retrieving the type by the getter.
@maaarghk  We patched it with
```
diff --color -Naur a/Api/Data/NotificationInterface.php b/Api/Data/NotificationInterface.php
--- a/Api/Data/NotificationInterface.php	2024-01-12 13:34:18.000000000 +0100
+++ b/Api/Data/NotificationInterface.php	2024-01-26 11:30:43.421672962 +0100
@@ -219,10 +219,10 @@
     public function getCreatedAt(): ?string;
 
     /**
-     * @param DateTime $createdAt
+     * @param string|DateTime $createdAt
      * @return NotificationInterface
      */
-    public function setCreatedAt(DateTime $createdAt): NotificationInterface;
+    public function setCreatedAt(string|DateTime $createdAt): NotificationInterface;
 
     /**
      * @return string|null
@@ -230,8 +230,8 @@
     public function getUpdatedAt(): ?string;
 
     /**
-     * @param DateTime $timestamp
+     * @param string|DateTime $timestamp
      * @return NotificationInterface
      */
-    public function setUpdatedAt(DateTime $timestamp): NotificationInterface;
+    public function setUpdatedAt(string|DateTime $timestamp): NotificationInterface;
 }
diff --color -Naur a/Model/Notification.php b/Model/Notification.php
--- a/Model/Notification.php	2024-01-24 16:28:56.955339943 +0100
+++ b/Model/Notification.php	2024-01-26 11:30:43.398672564 +0100
@@ -265,7 +265,7 @@
         return $createdAt;
     }
 
-    public function setCreatedAt(DateTime $createdAt): NotificationInterface
+    public function setCreatedAt(string|DateTime $createdAt): NotificationInterface
     {
         return $this->setData(self::CREATED_AT, $createdAt);
     }
@@ -274,14 +274,14 @@
     {
         $updatedAt = $this->getData(self::UPDATED_AT);
 
-        if ($updatedAt instanceOf Datetime) {
+        if ($updatedAt instanceof Datetime) {
             return $updatedAt->format('Y-m-d H:i:s');
         }
 
         return $updatedAt;
     }
 
-    public function setUpdatedAt(DateTime $timestamp): NotificationInterface
+    public function setUpdatedAt(string|DateTime $timestamp): NotificationInterface
     {
         return $this->setData(self::UPDATED_AT, $timestamp);
     }
```

**Comment by kpitn** [comment]
I add more information on this issue in the PR who introduce the bug (don't see this issue before)

https://github.com/Adyen/adyen-magento2/pull/220

I just install Adyen module.
Is version 9.x a beta version ?, do I need to install 8.x version ?
