### ISSUE TITLE
Original pspReference required for this operation

### ISSUE THREAD

**Issue by devkokov** [Adyen/adyen-magento2#374]
**Magento version**: 2.2.7
**Plugin version**: 2.4.3
**Description**

When creating an Invoice for a new order in the Admin panel, we get an error "We can't save the invoice right now."

The error in Magento's exception.log is

```
[2019-01-09 11:50:47] main.CRITICAL: Response does not exist {"exception":"[object] (InvalidArgumentException(code: 0): Response does not exist at /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-payment/Gateway/Helper/SubjectReader.php:76)"} []
```

The error in Adyen's error.log is

```
[2019-01-09 11:50:47] AdyenLoggerTest.ERROR: 167: Original pspReference required for this operation {"is_exception":false} []
[2019-01-09 11:50:47] AdyenLoggerTest.ERROR: Adyen\AdyenException: Original pspReference required for this operation in /var/www/vhosts/site/shared/www/magento2/vendor/adyen/php-api-library/src/Adyen/HttpClient/CurlClient.php:234
Stack trace:
#0 /var/www/vhosts/site/shared/www/magento2/vendor/adyen/php-api-library/src/Adyen/HttpClient/CurlClient.php(86): Adyen\HttpClient\CurlClient->handleResultError('{"status":422,"...', Object(Adyen\Payment\Logger\AdyenLogger))
#1 /var/www/vhosts/site/shared/www/magento2/vendor/adyen/php-api-library/src/Adyen/Service/AbstractResource.php(66): Adyen\HttpClient\CurlClient->requestJson(Object(Adyen\Service\Modification), 'https://pal-tes...', Array)
#2 /var/www/vhosts/site/shared/www/magento2/vendor/adyen/php-api-library/src/Adyen/Service/Modification.php(77): Adyen\Service\AbstractResource->request(Array)
#3 /var/www/vhosts/site/shared/www/magento2/vendor/adyen/module-payment/Gateway/Http/Client/TransactionCapture.php(73): Adyen\Service\Modification->capture(Array)
#4 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-payment/Gateway/Command/GatewayCommand.php(102): Adyen\Payment\Gateway\Http\Client\TransactionCapture->placeRequest(Object(Magento\Payment\Gateway\Http\Transfer))
#5 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-payment/Model/Method/Adapter.php(546): Magento\Payment\Gateway\Command\GatewayCommand->execute(Array)
#6 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-payment/Model/Method/Adapter.php(461): Magento\Payment\Model\Method\Adapter->executeCommand('capture', Array)
#7 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-sales/Model/Order/Payment/Operations/CaptureOperation.php(82): Magento\Payment\Model\Method\Adapter->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), '23')
#8 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-sales/Model/Order/Payment/Processor.php(85): Magento\Sales\Model\Order\Payment\Operations\CaptureOperation->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice))
#9 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-sales/Model/Order/Payment.php(467): Magento\Sales\Model\Order\Payment\Processor->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice))
#10 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-sales/Model/Order/Invoice.php(344): Magento\Sales\Model\Order\Payment->capture(Object(Magento\Sales\Model\Order\Invoice))
#11 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-sales/Model/Order/Invoice.php(618): Magento\Sales\Model\Order\Invoice->capture()
#12 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-sales/Controller/Adminhtml/Order/Invoice/Save.php(173): Magento\Sales\Model\Order\Invoice->register()
#13 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/App/Action/Action.php(107): Magento\Sales\Controller\Adminhtml\Order\Invoice\Save->execute()
#14 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-backend/App/AbstractAction.php(235): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Invoice\Save\Interceptor->___callParent('dispatch', Array)
#17 /var/www/vhosts/site/shared/www/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Sales\Controller\Adminhtml\Order\Invoice\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Sales\Controller\Adminhtml\Order\Invoice\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Invoice\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/vhosts/site/shared/www/magento2/generated/code/Magento/Sales/Controller/Adminhtml/Order/Invoice/Save/Interceptor.php(26): Magento\Sales\Controller\Adminhtml\Order\Invoice\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#21 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\Sales\Controller\Adminhtml\Order\Invoice\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#24 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/vhosts/site/shared/www/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#26 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /var/www/vhosts/site/shared/www/magento2/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#28 /var/www/vhosts/site/shared/www/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#29 {main} {"is_exception":true} []
```

We use Hosted Payment Page in test mode with test card details (VISA).

Any help would be much appreciated!

**Comment by devkokov** [comment]
I found the cause of the problem.

I had redirected the site to HTTPS and my Server Communication in Adyen's portal had stopped working, as it had been configured for HTTP.

Because of this, Magento wasn't aware that the payment had been captured, and therefore it wasn't creating an invoice automatically.

When I try to create an invoice manually, there is a dropdown at the bottom that defaults to "Capture Online". When this is selected I get the error message above. If I change the dropdown to "Do not capture" the invoice gets created correctly.

I've fixed my Server Communication settings in Adyen and now everything works fine, I don't even have to create the invoice manually.

Totally a user error on my part, but if I have to be critical maybe a more meaningful error message would've helped me identify and fix the problem sooner.

**Comment by meandor-ua** [comment]
It could be the problem of Adyen webhook logic. In 8.2.4 version we faced the same issue.
It appeared that in \Adyen\Payment\Helper\Webhook::prepareInvoice payment method object $paymentObj is only populated, but not saved. That cause issues with transactions like capture, which require pspReference, which is taken from payment (cc_trans_id). One additional row with
`$paymentObj->save();`
may fix an issue for new orders.
For existing orders one could find PSP Reference from different places such as sales_order_payment (additional_data),  sales_payment_transaction (txn_id) or adyen_order_payment (pspreference).
Setting pspReference to fileds into cc_trans_id and last_trans_id of sales_order_payment DB table may fix issues with capture for existing orders.
