### ISSUE TITLE
Install the plugin in a clean magento 2 breaks the checkout page

### ISSUE THREAD

**Issue by hkvega01** [Adyen/adyen-magento2#751]
**Describe the bug**
Install the plugin (lastest master branch) into a clean magento 2.3.4 (ce or commerce also tried) 

**To Reproduce**
1. Install the plugin, fill in all required fields in backend
2. create a product in backend
3. add product into a cart as guest
4. go to checkout page
5. the page only displays the loading icon

**Expected behavior**
show checkout page

**Screenshots**
![adyen](https://user-images.githubusercontent.com/4374758/86082402-3b57ee80-baca-11ea-937b-3b936f319b3f.JPG)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]

Remarks: there is nothing error message i can find in any exception

**Comment by acampos1916** [comment]
Hello @hkvega01,

Have you checked the Magento and webserver logs for errors? You could also try running Magento in developer mode to see extra output.

Does the loading icon display in the shipping address step of the checkout page?

Cheers,
Ángel

**Comment by hkvega01** [comment]
@acampos1916 
i've the following error logs
```
#5 /home/m234magento/public_html/vendor/magento/module-checkout/Block/Onepage.php(106): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#6 /home/m234cl in /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php on line 1529
[30-Jun-2020 07:27:18 UTC] PHP Fatal error:  Uncaught Error: Class 'Adyen\Client' not found in /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php:1529
Stack trace:
#0 /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php(1495): Adyen\Payment\Helper\Data->createAdyenClient()
#1 /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php(1588): Adyen\Payment\Helper\Data->initializeAdyenClient('1')
#2 /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php(1564): Adyen\Payment\Helper\Data->getOriginKeyForOrigin('http://m234clea...', '1')
#3 /home/m234magento/public_html/app/code/Adyen/Payment/Model/Ui/AdyenCcConfigProvider.php(160): Adyen\Payment\Helper\Data->getOriginKeyForBaseUrl()
#4 /home/m234magento/public_html/vendor/magento/module-checkout/Model/CompositeConfigProvider.php(39): Adyen\Payment\Model\Ui\AdyenCcConfigProvider->getConfig()
#5 /home/m234magento/public_html/vendor/magento/module-checkout/Block/Onepage.php(106): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#6 /home/m234cl in /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php on line 1529
[30-Jun-2020 08:20:05 UTC] PHP Fatal error:  Uncaught Error: Class 'Adyen\Client' not found in /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php:1529
Stack trace:
#0 /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php(1495): Adyen\Payment\Helper\Data->createAdyenClient()
#1 /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php(1588): Adyen\Payment\Helper\Data->initializeAdyenClient('1')
#2 /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php(1564): Adyen\Payment\Helper\Data->getOriginKeyForOrigin('http://m234clea...', '1')
#3 /home/m234magento/public_html/app/code/Adyen/Payment/Model/Ui/AdyenCcConfigProvider.php(160): Adyen\Payment\Helper\Data->getOriginKeyForBaseUrl()
#4 /home/m234magento/public_html/vendor/magento/module-checkout/Model/CompositeConfigProvider.php(39): Adyen\Payment\Model\Ui\AdyenCcConfigProvider->getConfig()
#5 /home/m234magento/public_html/vendor/magento/module-checkout/Block/Onepage.php(106): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#6 /home/m234cl in /home/m234magento/public_html/app/code/Adyen/Payment/Helper/Data.php on line 1529
```

**Comment by acampos1916** [comment]
Hello @hkvega01,

Since you installed the plugin from the source repository your system is missing the dependency on the adyen/php-api-library package. You can use Composer to install the desired plugin version automatically with its dependencies or resolve them manually by installing the required packages from the composer.json file.

Let us know if you face any other issues,
Ángel
